spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    # driver-class-name: ${db.driver}

    ${DB_PASSWORD} = ${db.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: ${db.type}
    database-platform: ${db.platform}

  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: env

server:
  port: ${server-port}
  servlet:
    contextPath: ${prefix-path}

logging:
  level:
    org.springframework.security: DEBUG