prefix-path: /api/v1
server-port: 8888
hash-sceret: FPNCXXTTAODDGNFKXPRVIMOKGUVGVZTC
tmn-code: 1X6BJ2DP

db:
  url: jdbc:mysql://localhost:3306/hph_db
  username: root
  password: root
  driver: com.mysql.jdbc.Driver
  type: mysql
  platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 day || # a day 86400000
      refresh-token:
        expiration: 604800000 # 7 days

mail:
  username: nguyenquangloi2704@gmail.com
  password: ceyknqpiwkmudedw
  host: smtp.gmail.com
  port: 587

frontend:
  url: http://hph.quachuoitrenmay.online

cors:
  allowed-origins: >
    http://localhost:5173,
    http://localhost:3000,
    http://localhost:8888,
    http://hph.quachuoitrenmay.online,
    https://hph.quachuoitrenmay.online,

  allowed-methods: >
    GET,
    POST,
    PUT,
    DELETE,

  allowed-headers: >
    *,
