db:
  url: jdbc:mysql://localhost:3306/hph_db
  username: root
  password: 1
  driver: com.mysql.jdbc.Driver
server:
  port: 8888

mail:
  username: nguyenquangloi2704@gmail.com
  password: ceyknqpiwkmudedw

frontend:
  url: http://localhost:5173

spring:
  mvc:
    cors:
      mapping:
        - /** # Apply CORS configuration to all endpoints
      allowed-origins:
        - http://allowed-origin.com # Add the allowed origins here
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - "*" # Allow all headers