db:
  url: jdbc:mysql://localhost:3306/hph_db1
  username: root
  password: 1
  driver: com.mysql.jdbc.Driver

port: 8888

mail:
  username: nguyenquangloi2704@gmail.com
  password: ceyknqpiwkmudedw

frontend:
  url: http://localhost:5173