apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hph
  name: backend-sit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container-02
          image: quachuoiscontainer/hph_be:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi"
              cpu: "1000m"