apiVersion: v1
kind: Service
metadata:
  namespace: hph
  name: backend-sit-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer